version: 2.1
jobs:
  semgrep-scan:
    parameters:
      repo_path:
        type: string
        default: ${CIRCLE_BRANCH}
      default_branch:
        type: string
        default: master
    environment:
      SEMGREP_RULES: >- # more at semgrep.dev/explore
        p/security-audit
        p/secrets

      # Scan changed files in PRs, block on new issues only (existing issues ignored)
      #SEMGREP_BASELINE_REF: << parameters.default_branch >>

    # == Optional settings in the `environment:` block

    # Instead of `SEMGREP_RULES:`, use rules set in Semgrep App.
    # Get your token from semgrep.dev/manage/settings.
    #   SEMGREP_APP_TOKEN: $SEMGREP_APP_TOKEN
    #   SEMGREP_REPO_NAME: << parameters.repo_path >>
    #   SEMGREP_REPO_URL: << pipeline.project.git_url >>
    #   SEMGREP_BRANCH: << pipeline.git.branch >>

    # Never fail the build due to findings.
    # Instead, just collect findings for semgrep.dev/manage/findings
    #   SEMGREP_AUDIT_ON: unknown

    # Change job timeout (default is 1800 seconds; set to 0 to disable)
    #   SEMGREP_TIMEOUT: 300
      SEMGREP_AUDIT_ON: unknown
    docker:
      - image: returntocorp/semgrep-agent:v1
    steps:
      - checkout
      - run:
          name: "Semgrep scan"
          command: semgrep-agent

  testing-scan:
      docker: 
          - image: alpine:3.7
      steps:
          - run: echo "Hello"
          
  secret-scan:
      docker:
          - image: circleci/python:latest
      #working_directory: ~/repo
      steps:
          - checkout
          - run: sudo pip install trufflehog
          - run: trufflehog --max_depth 1 ~/

      
workflows:
  main:
    jobs:
      - semgrep-scan
      - testing-scan
      - secret-scan