version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu-latest
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'

  security-scan:
    parameters:
      repo_path:
        type: string
        default: ${CIRCLE_BRANCH}
      default_branch:
        type: string
        default: ${CIRCLE_BRANCH}
    environment:
      SEMGREP_RULES: >- # more at semgrep.dev/explore
        p/security-audit
        p/secrets

      # Scan changed files in PRs, block on new issues only (existing issues ignored)
      SEMGREP_BASELINE_REF: << parameters.default_branch >>


    docker:
        - image: returntocorp/semgrep-agent:v1
    steps:
      - checkout
      - run:
          name: "Semgrep scan"
          command: semgrep-agent
